# GitHub label config for express-chocolatey-server
# These are the labels unique to the project.  See common.yaml for labels that
# all projects share.


- import: ../common/common.yaml


# Deployment environments
# -----

- name: "environment: App Engine"
  # No alias; did not exist before
  description: An issue with App Engine deployment
  color: c2e0c6

- name: "environment: standalone"
  # No alias; did not exist before
  description: An issue with standalone deployment
  color: c2e0c6

- name: "environment: other"
  # No alias; did not exist before
  description: An issue with some other type of deployment
  color: c2e0c6
