# GitHub label config for webdriver-installer
# These are the labels unique to the project.  See common.yaml for labels that
# all projects share.


- import: ../common/common.yaml
- import: ../common/browsers.yaml
