name: Test Update Issues Tool

on:
  pull_request: # Trigger for pull requests.
    types: [opened, synchronize, reopened]
    paths:
      update-issues/**
  workflow_dispatch: # Allows for manual triggering.
    inputs:
      ref:
        description: "The ref to build and test."
        required: False

jobs:
  test:
    name: Test Update Issues Tool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Test
        run: |
          cd update-issues
          npm ci
          npm test
